name: PickupChest
version: 1.2 #'${project.version}'
main: com.msicraft.pickupchest.PickupChest
api-version: 1.16
authors: [ msicraft ]
softdepend: [Towny, WorldGuard, GriefPrevention]
description: Allow pickup chest
commands:
  pickupchest:
    description: Main command
    aliases: [puc]
    permission-message: You don't have permission
permissions:
  pickupchest.command:
    description: Allow command
    default: op
